C++ code formatter
StasDzundza/metaprogramming pull request #1
Opened 2020-10-18 20:53 UTC by StasDzundza

2020-10-19 18:33 UTC, hoherchak requested changes
Врахуйте зауваження по конфігурації. Також перевірте роботу для такого коду:
```
template<class T> struct FooT { char g(); hash<int, list<char> > elems; template<int N> int foo() { return N; } template<> int foo<2>() { return Min<>(1, 5); } list<int> mem = {1, 2, 3}; float vector[3] = {}; FooT() : elems{{-1, {'c', 'p', 'p'}}, {1,  {'j', 'b'}}}, vector{1f, 2f, 3f} {} FooT operator++(int) volatile { return *this; } auto f(T t) -> decltype(t + g()) { return t + g(); } };
```
Трохи поплило форматування.
Також в логах мають бути відображені помилки форматування.
Щодо власне утиліти – ви випустили дві вкладки параметрів: wrapping and braces (це по суті розташування дужок різного типу відносно елементів коду) та blank lines (обмеження на кількість порожніх рядків).
І ще прохання форматувати код у самому файлі, не створюючи новий.

2020-10-19 18:33 UTC, hoherchak commented on cpp_code_formatter/config.json
> +	"preprocessor_directive_indent": 0,
Чомусь таб після #

2020-10-19 18:33 UTC, hoherchak commented on cpp_code_formatter/config.json
> +	"indent_member_of_classes": 4,
Не бачу впливу цього параметру

2020-10-19 18:33 UTC, hoherchak commented on cpp_code_formatter/config.json
> +	"func_decl_parenthesis" : 0,
Впливає одразу і на декларацію, і на виклик і чомусь на неймспейс

2020-10-19 18:33 UTC, hoherchak commented on cpp_code_formatter/config.json
> +	"before_function_left_brace" : 1,
Чомусь цей параметр нічого не змінює

2020-10-19 18:33 UTC, hoherchak commented on cpp_code_formatter/config.json
> +	"within_empty_template_declaration" : 0,
Зверніть увагу на `template < typename K , class V=list<K > >` - це результат всіх одиниць, перед К пробілу немає.

2020-10-19 18:33 UTC, hoherchak commented on cpp_code_formatter/config.json
> +	"within_empty_template_instantiation" : 0
Ці параметри ні на що не впливають.

2020-10-25 13:12 UTC, StasDzundza commented on cpp_code_formatter/config.json
> +	"preprocessor_directive_indent": 0,
fixed

2020-10-25 13:12 UTC, StasDzundza commented on cpp_code_formatter/config.json
> +	"indent_member_of_classes": 4,
Fixed

2020-10-25 13:12 UTC, StasDzundza commented on cpp_code_formatter/config.json
> +	"func_decl_parenthesis" : 0,
fixed

2020-10-25 13:13 UTC, StasDzundza commented on cpp_code_formatter/config.json
> +	"before_function_left_brace" : 1,
fixed

2020-10-25 13:13 UTC, StasDzundza commented on cpp_code_formatter/config.json
> +	"within_empty_template_declaration" : 0,
fixed

2020-10-25 13:13 UTC, StasDzundza commented on cpp_code_formatter/config.json
> +	"within_empty_template_instantiation" : 0
fixed

2020-10-25 19:32 UTC, hoherchak requested changes
Форматування кульгає наприклад на цьому прикладі:
```
#include <stdio.h> #define min(a, b)  ((a) < (b) ? (a) : (b)) template<typename T, typename M> inline T const &Min(T const &a, M const &b) { return a < b ? a : b; } template<typename T> class list { }; template<typename K, typename V = list<K> > class hash { }; template<class T> struct FooT { char g(); hash<int, list<char> > elems; template<int N> int foo() { return N; } template<> int foo<2>() { return Min<>(1, 5); } list<int> mem = {1, 2, 3}; float vector[3] = {}; FooT() : elems{{-1, {'c', 'p', 'p'}}, {1,  {'j', 'b'}}}, vector{1f, 2f, 3f} {} FooT operator++(int) volatile { return *this; } auto f(T t) -> decltype(t + g()) { return t + g(); } }; class Bar { }; struct FooBase { }; int doSomething(...) { return 1; } struct Foo : private FooBase { public: int i; Foo(const Foo &) = delete; Foo &operator=(const Foo &) = default; void log() volatile &; virtual int action(int, char, float) = 0; virtual Foo *getSelf() const { return this; } private: static int method() {}; }; namespace fooNS { class FooClass : Foo, virtual FooBase { typedef int (FooClass::*ACTION)(int); public: FooClass() { act = &FooClass::nv_action; } virtual ~FooClass() {}; int nv_action(int arg) { return arg; } virtual int action(int color, char alpha, float); virtual Foo *getSelf() { return Foo::getSelf(); } int method() { FooT<int> bar; int X[] = {1, 3, 5, 6, 7, 87, 1213, 2}; int W[][3] = {{1, 3, 5}, {6, 7, 8}}; int y = 0, x; auto la = [X, W](int i1, int i2) -> bool mutable { return i1 < i2; }(1, 2); auto laF = []() {}; bool z = (bar.foo<2>() & 4) == 4; for (int i = 0; i < x; i++) { y += (y ^ 0x123) << 2; } do { try { if (0 < x && x < 10) { while (x != y) { x = min(x * 3, 5); } x = x >= 5 ?: 5; } else if (min(1, 5) == 1) { switch (this->action(0xFeeL, 0120, 0.01F)) { default: break; case 1: continue; } } } catch (char *message) { const int *arr = X; x = ((y >= 0) ? arr[y] : -1); } } while (true); } ACTION act; private: int var; }; } int fooNS::FooClass::action(int color, char alpha, float) { fooNS::FooClass object, *ptr = (fooNS::FooClass *) object.getSelf()->getSelf()->getSelf(); (object.*object.act)(1); ptr->action(10001, '\x1A', 1e13f); ptr->getSelf()->getSelf()->getSelf()->getSelf(); return doSomething(color); } typedef void(fn)(int i, int j, int k); typedef void(*block)(int i, int j, int k); typedef int X; int &refTest(X &&x, int y, int b, void *(*)()) { int **&p = (int **&) x; int static &r = *&x; return r && (r & x) ? r : x; } struct fooS { int i: 4; char j; } foo_t; enum fooE { SUNDAY = 111, MONDAY = 222, TUESDAY = 333, WEDNESDAY = TUESDAY + 1 } foo_e;
```
Плюс чомусь конкатенуються else та наступний if, місцями типи з наступною назвою змінної тощо.
Пунктів в wrappind and braces мало, також немає пунктів з блоку максимальної кількості рядків.

2020-10-25 21:01 UTC, hoherchak approved these changes
Готуйтесь до захисту на найближчій парі.

2020-11-02 22:26 UTC, merged