Code Style Checker(Lab2)
StasDzundza/metaprogramming pull request #2
Opened 2020-11-13 00:30 UTC by StasDzundza

2020-11-15 20:57 UTC, hoherchak requested changes
Виправте помилку опрацювання такого коду:
```
//
// main_http.cpp
// web_server
// created by changkun at changkun.de
// https://github.com/changkun/modern-cpp-tutorial/
//

#include <iostream>
#include "server.http.hpp"
#include "handler.hpp"

using namespace Web;

int main() {
    // HTTP server runs in port 12345 HTTP, enable 4 threads
    Server<HTTP> server(12345, 4);
    std::cout << "Server starting at port: 12345" << std::endl;
    start_server<Server<HTTP>>(server);
    return 0;
}
```
і тут:
```
//
// 2.1.nullptr.cpp
// chapter 2 language usability
// modern cpp tutorial
//
// created by changkun at changkun.de
// https://github.com/changkun/modern-cpp-tutorial
//

#include <iostream>
#include <type_traits>

void foo(char *);
void foo(int);

int main() {
    if (std::is_same<decltype(NULL), decltype(0)>::value)
        std::cout << "NULL == 0" << std::endl;
    if (std::is_same<decltype(NULL), decltype((void*)0)>::value)
        std::cout << "NULL == (void *)0" << std::endl;
    if (std::is_same<decltype(NULL), std::nullptr_t>::value)
        std::cout << "NULL == nullptr" << std::endl;

    foo(0);          // will call foo(int)
    // foo(NULL);    // doesn't compile
    foo(nullptr);    // will call foo(char*)
    return 0;
}

void foo(char *) {
    std::cout << "foo(char*) is called" << std::endl;
}
void foo(int i) {
    std::cout << "foo(int) is called" << std::endl;
}
```
Плюс подумайте над тим, як краще вирізняти функція в бібліотеці чи ні. У ваших прикладах якщо викликати умовний std::foo(), він теж перейменується, а не має.

2020-11-16 23:32 UTC, StasDzundza commented
> Виправте помилку опрацювання такого коду:
> 
> ```
> //
> // main_http.cpp
> // web_server
> // created by changkun at changkun.de
> // https://github.com/changkun/modern-cpp-tutorial/
> //
> 
> #include <iostream>
> #include "server.http.hpp"
> #include "handler.hpp"
> 
> using namespace Web;
> 
> int main() {
>     // HTTP server runs in port 12345 HTTP, enable 4 threads
>     Server<HTTP> server(12345, 4);
>     std::cout << "Server starting at port: 12345" << std::endl;
>     start_server<Server<HTTP>>(server);
>     return 0;
> }
> ```
> 
> і тут:
> 
> ```
> //
> // 2.1.nullptr.cpp
> // chapter 2 language usability
> // modern cpp tutorial
> //
> // created by changkun at changkun.de
> // https://github.com/changkun/modern-cpp-tutorial
> //
> 
> #include <iostream>
> #include <type_traits>
> 
> void foo(char *);
> void foo(int);
> 
> int main() {
>     if (std::is_same<decltype(NULL), decltype(0)>::value)
>         std::cout << "NULL == 0" << std::endl;
>     if (std::is_same<decltype(NULL), decltype((void*)0)>::value)
>         std::cout << "NULL == (void *)0" << std::endl;
>     if (std::is_same<decltype(NULL), std::nullptr_t>::value)
>         std::cout << "NULL == nullptr" << std::endl;
> 
>     foo(0);          // will call foo(int)
>     // foo(NULL);    // doesn't compile
>     foo(nullptr);    // will call foo(char*)
>     return 0;
> }
> 
> void foo(char *) {
>     std::cout << "foo(char*) is called" << std::endl;
> }
> void foo(int i) {
>     std::cout << "foo(int) is called" << std::endl;
> }
> ```
> 
> Плюс подумайте над тим, як краще вирізняти функція в бібліотеці чи ні. У ваших прикладах якщо викликати умовний std::foo(), він теж перейменується, а не має.

Виправив помилку форматування імен в шаблонах.
Покращив форматування коментарів. Тепер порожні коментарі типу // зникають.
Покращив розпізнавання декларацій. Тепер умовне std::foo не буде форматуватись.
Пофіксив баг із занесенням неймспейса до задекларованого, якщо він був об'явлений за допомогою using.
Також дрібні фікси лексера та форматувальника.
Залив нову версію(1.0.2) на PyPi.

2020-11-17 08:48 UTC, hoherchak requested changes
При обробці modern-cpp-tutorial виникає виключення:
```
Traceback (most recent call last):
  File "/Users/hryhoriihoherchak/Documents/labs/Dzundza/metaprogramming/venv/bin/cpp_code_style_formatter", line 5, in <module>
    from cpp_code_style_formatter.__main__ import main
  File "/Users/hryhoriihoherchak/Documents/labs/Dzundza/metaprogramming/venv/lib/python3.8/site-packages/cpp_code_style_formatter/__main__.py", line 9, in <module>
    main()
  File "/Users/hryhoriihoherchak/Documents/labs/Dzundza/metaprogramming/venv/lib/python3.8/site-packages/cpp_code_style_formatter/__main__.py", line 7, in main
    run_style_checker(sys.argv)
  File "/Users/hryhoriihoherchak/Documents/labs/Dzundza/metaprogramming/venv/lib/python3.8/site-packages/cpp_code_style_formatter/code_style_checker_runner.py", line 12, in run_style_checker
    code_style_checker.run_for_project("-f", command_line_args[3])
  File "/Users/hryhoriihoherchak/Documents/labs/Dzundza/metaprogramming/venv/lib/python3.8/site-packages/cpp_code_style_formatter/code_style_checker.py", line 357, in run_for_project
    self.run_for_file(mode, file, False)
  File "/Users/hryhoriihoherchak/Documents/labs/Dzundza/metaprogramming/venv/lib/python3.8/site-packages/cpp_code_style_formatter/code_style_checker.py", line 383, in run_for_file
    self.fix_code_style(file_path, WorkingMode.FixMode)
  File "/Users/hryhoriihoherchak/Documents/labs/Dzundza/metaprogramming/venv/lib/python3.8/site-packages/cpp_code_style_formatter/code_style_checker.py", line 73, in fix_code_style
    if prev_prev_token is not None and (prev_prev_token.value in self.defined_type_names or
UnboundLocalError: local variable 'prev_prev_token' referenced before assignment
```
Також перевірте роботу з R-string'ами.

2020-11-19 19:03 UTC, hoherchak approved these changes

2020-11-20 12:36 UTC, merged